### ISSUE TITLE
Layout issues with EM after node deletion or node hiding

### ISSUE THREAD

**Issue by risserlin** [BaderLab/EnrichmentMapApp#67]
After deleting nodes or hiding nodes from a network using the EM slider bars when you re-layout the network there is often a large gap between the connected components and the rest of the cliques and single nodes.

**Comment by mikekucera** [comment]
Is this mainly a concern with the force-directed layout? 

It seems some layouts ignore hidden nodes while some do not. But the force-directed layout behaves strangely. I get different results when nodes are hidden, but there are large gaps around hidden nodes. I don't think its fully ignoring the nodes. Its probably a bug.

**Comment by risserlin** [comment]
Force directed is the default layout that EM uses.

Is this a cytoscape issue?  Is it fixed in 3.3.  I know that Christian fixed this same issue for gene mania.

**Comment by mikekucera** [comment]
I'll ask him.

**Comment by mikekucera** [comment]
This is a cytoscape issue. Its not fixed yet. Christian and I plan to fix it in 3.3. The fix Christian used for geme mania was kind of a hack, we want to fix this properly in cytoscape.

I'm going to take this issue off the 2.1 milestone as it will have to wait for 3.3.

**Comment by mikekucera** [comment]
Pushed to Cytoscape 3.4
https://code.cytoscape.org/redmine/issues/2745

**Comment by mikekucera** [comment]
Fixed in Cytoscape 3.4
